# Generated by Django 5.1.4 on 2025-03-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0002_consultationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона'),
        ),
    ]
